### ISSUE TITLE
About updating to zig master

### ISSUE THREAD

**Issue by iddev5** [Vexu/bog#18]
Hello,

I have been trying to port this project over to zig master from the past couple days. While I am already successful in it and all tests are passing, there is a small problem. AutoIndentingStream is removed from std lib in recent versions. For tests, I ended up copying the same source code over to here (and made slight modifications), but concern is licensing.

How I should go about from here? I have been considering somehow remaking the AIS...

My branch is here: https://github.com/iddev5/bog/tree/fix-build it is complete minus cleanup/zig fmt

Thank you.

**Comment by Vexu** [comment]
> How I should go about from here? I have been considering somehow remaking the AIS...

Just copy the implementation from `lib/std/zig/render.zig` that's what I did in my [branch](https://github.com/Vexu/bog/tree/bog2) where I'm reworking much of the language. I have no idea when if ever I'll finish that branch so I'd be happy to accept a pr to fix the build in the meanwhile.
